"use strict";var Q=Object.create;var S=Object.defineProperty;var z=Object.getOwnPropertyDescriptor;var K=Object.getOwnPropertyNames;var W=Object.getPrototypeOf,Z=Object.prototype.hasOwnProperty;var ee=(e,t)=>{for(var r in t)S(e,r,{get:t[r],enumerable:!0})},E=(e,t,r,o)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of K(t))!Z.call(e,i)&&i!==r&&S(e,i,{get:()=>t[i],enumerable:!(o=z(t,i))||o.enumerable});return e};var w=(e,t,r)=>(r=e!=null?Q(W(e)):{},E(t||!e||!e.__esModule?S(r,"default",{value:e,enumerable:!0}):r,e)),te=e=>E(S({},"__esModule",{value:!0}),e);var de={};ee(de,{default:()=>X});module.exports=te(de);var k=require("react"),n=require("@raycast/api"),d=w(require("path"));var L=w(require("crypto")),T=new Uint8Array(256),O=T.length;function C(){return O>T.length-16&&(L.default.randomFillSync(T),O=0),T.slice(O,O+=16)}var a=[];for(let e=0;e<256;++e)a.push((e+256).toString(16).slice(1));function N(e,t=0){return a[e[t+0]]+a[e[t+1]]+a[e[t+2]]+a[e[t+3]]+"-"+a[e[t+4]]+a[e[t+5]]+"-"+a[e[t+6]]+a[e[t+7]]+"-"+a[e[t+8]]+a[e[t+9]]+"-"+a[e[t+10]]+a[e[t+11]]+a[e[t+12]]+a[e[t+13]]+a[e[t+14]]+a[e[t+15]]}var b=w(require("crypto")),$={randomUUID:b.default.randomUUID};function ne(e,t,r){if($.randomUUID&&!t&&!e)return $.randomUUID();e=e||{};let o=e.random||(e.rng||C)();if(o[6]=o[6]&15|64,o[8]=o[8]&63|128,t){r=r||0;for(let i=0;i<16;++i)t[r+i]=o[i];return t}return N(o)}var P=ne;var v=w(require("net")),D=require("child_process"),M=w(require("path")),F=w(require("os")),I=require("@raycast/api"),q="com.lightningocr.daemon",ie=M.default.join(F.default.homedir(),"Library","LaunchAgents",`${q}.plist`),re=3e3,A=3e4,oe=2e3;function ae(){try{return(0,I.getPreferenceValues)().socketPath||"/tmp/lightningocr.sock"}catch{return"/tmp/lightningocr.sock"}}function U(e,t){return new Promise((r,o)=>{let i=v.default.createConnection({path:e}),p="",s=!1,m=setTimeout(()=>{s||(s=!0,i.destroy(),o(new Error("Request timed out after "+A+"ms")))},A),g=setTimeout(()=>{s||(s=!0,i.destroy(),o(new Error("DAEMON_NOT_RUNNING")))},re);i.on("connect",()=>{clearTimeout(g);let c=JSON.stringify(t)+`
`;i.write(c)}),i.on("data",c=>{p+=c.toString();let f=p.indexOf(`
`);if(f!==-1){clearTimeout(m);let R=p.slice(0,f);if(i.end(),!s){s=!0;try{r(JSON.parse(R))}catch{o(new Error(`Failed to parse daemon response: ${R}`))}}}}),i.on("error",c=>{if(clearTimeout(m),clearTimeout(g),!s){s=!0;let f=c.message||String(c);f.includes("ENOENT")||f.includes("ECONNREFUSED")?o(new Error("DAEMON_NOT_RUNNING")):o(c)}}),i.on("close",()=>{clearTimeout(m),clearTimeout(g)})})}function se(){try{(0,D.execSync)(`launchctl load -w "${ie}" 2>/dev/null || launchctl kickstart -k gui/$(id -u)/${q} 2>/dev/null || true`)}catch{}}function ce(e){return new Promise(t=>setTimeout(t,e))}async function H(e){let t=ae();try{return await U(t,e)}catch(r){if((r instanceof Error?r.message:String(r))==="DAEMON_NOT_RUNNING"){se(),await ce(oe);try{return await U(t,e)}catch{throw new Error("LightningOCR daemon is not running. Run `./scripts/install.sh` to set it up, or start it manually with: python daemon/server.py")}}throw r}}var V=[".png",".jpg",".jpeg",".webp",".tiff",".tif",".heic",".bmp"];function j(e){return V.includes(d.default.extname(e).toLowerCase())}function le(e){let t=[];return[...e.matchAll(/\$\$([\s\S]+?)\$\$/g)].forEach(i=>t.push(i[1].trim())),[...e.matchAll(/(?<!\$)\$(?!\$)([\s\S]+?)(?<!\$)\$(?!\$)/g)].forEach(i=>t.push(i[1].trim())),t.join(`

`)}function me(e){let t=e;return t=t.replace(/\$\$[\s\S]+?\$\$/g,""),t=t.replace(/(?<!\$)\$(?!\$)[\s\S]+?(?<!\$)\$(?!\$)/g,""),t.replace(/\n{3,}/g,`

`).trim()}function ue(e){return e>=.95?"\u{1F7E2}":e>=.8?"\u{1F7E1}":"\u{1F534}"}function G(e){switch(e){case"text":return"Vision Text";case"formula":return"MFR Formula";case"mixed":return"Layout + Mixed";default:return e??"auto"}}function X(){let e=(0,n.getPreferenceValues)(),[t,r]=(0,k.useState)({kind:"selecting"});(0,k.useEffect)(()=>{o()},[]);async function o(){r({kind:"selecting"});let u=null;try{let x=(await(0,n.getSelectedFinderItems)()).find(Y=>j(Y.path));x&&(u=x.path)}catch{}if(!u){await(0,n.showToast)({style:n.Toast.Style.Animated,title:"Select an image in Finder",message:"Then re-run this command, or open Finder and select an image first."});try{await(0,n.open)("/")}catch{}r({kind:"error",message:"No image selected. Select an image file in Finder and run this command again."});return}if(!j(u)){let l=`Unsupported file type: ${d.default.extname(u)}. Supported: ${V.join(", ")}`;r({kind:"error",message:l}),await(0,n.showToast)({style:n.Toast.Style.Failure,title:"Unsupported file",message:l});return}r({kind:"ocr_running",filePath:u}),await(0,n.showToast)({style:n.Toast.Style.Animated,title:"Running OCR\u2026",message:d.default.basename(u)});let J=Date.now(),y;try{y=await H({id:P(),operation:"ocr",image_path:u,mode:"auto",quality:e.quality})}catch(l){let x=l instanceof Error?l.message:String(l);r({kind:"error",message:x}),await(0,n.showToast)({style:n.Toast.Style.Failure,title:"OCR failed",message:x});return}let _=Date.now()-J;if(y.status==="error"){let l=y.error??"Unknown daemon error";r({kind:"error",message:l}),await(0,n.showToast)({style:n.Toast.Style.Failure,title:"OCR failed",message:l});return}r({kind:"done",result:y,filePath:u,latencyMs:_}),await(0,n.showToast)({style:n.Toast.Style.Success,title:y.status==="low_confidence"?"\u26A0 Low confidence":"\u2713 OCR complete",message:`${y.latency_ms??_}ms  \xB7  Press \u21B5 to copy`})}if(t.kind==="selecting")return _jsx(n.Detail,{isLoading:!0,markdown:"## LightningOCR\\n\\n\u23F3 Looking for selected Finder image\u2026",navigationTitle:"OCR Image File"});if(t.kind==="ocr_running")return _jsx(n.Detail,{isLoading:!0,markdown:`## LightningOCR

\u23F3 Running OCR on **${d.default.basename(t.filePath)}**\u2026`,navigationTitle:"OCR Image File"});if(t.kind==="error")return _jsx(n.Detail,{markdown:`## \u274C Error

${t.message}`,navigationTitle:"OCR Image File",actions:_jsx(n.ActionPanel,null,_jsx(n.Action,{title:"Retry",onAction:o}))});let{result:i,filePath:p,latencyMs:s}=t,m=i.markdown??"",g=i.confidence??0,c=le(m),f=me(m),R=i.cache_hit??!1,h=[];e.showConfidence&&h.push(`${ue(g)} Confidence: **${(g*100).toFixed(1)}%**`),h.push(`\u{1F4C4} \`${d.default.basename(p)}\``),h.push(`\u26A1 ${R?"Cache hit":`${i.latency_ms??s} ms`}  \xB7  Route: ${G(i.route)}`),i.status==="low_confidence"&&h.push("\u26A0\uFE0F  Low confidence \u2014 result may contain errors");let B=`${h.join(`  
`)}

---

${m}`;return _jsx(n.Detail,{markdown:B,navigationTitle:`OCR \u2014 ${d.default.basename(p)}`,metadata:_jsx(n.Detail.Metadata,null,_jsx(n.Detail.Metadata.Label,{title:"File",text:d.default.basename(p)}),_jsx(n.Detail.Metadata.Label,{title:"Route",text:G(i.route)}),_jsx(n.Detail.Metadata.Label,{title:"Confidence",text:`${(g*100).toFixed(1)}%`}),_jsx(n.Detail.Metadata.Label,{title:"Latency",text:R?"Cache hit":`${i.latency_ms??s} ms`})),actions:_jsx(n.ActionPanel,null,_jsx(n.ActionPanel.Section,{title:"Copy"},_jsx(n.Action,{title:"Copy Markdown",shortcut:{modifiers:[],key:"return"},onAction:async()=>{await n.Clipboard.copy(m),await(0,n.showHUD)("\u2713 Markdown copied")}}),_jsx(n.Action,{title:"Copy Plain Text",shortcut:{modifiers:["cmd"],key:"return"},onAction:async()=>{await n.Clipboard.copy(f),await(0,n.showHUD)("\u2713 Plain text copied")}}),c&&_jsx(n.Action,{title:"Copy LaTeX Only",shortcut:{modifiers:["cmd","shift"],key:"c"},onAction:async()=>{await n.Clipboard.copy(c),await(0,n.showHUD)("\u2713 LaTeX copied")}})),_jsx(n.ActionPanel.Section,{title:"Actions"},_jsx(n.Action,{title:"Re-run OCR",shortcut:{modifiers:["cmd"],key:"r"},onAction:o})))})}
